#!/bin/sh

cd /tmp

wget https://codeload.github.com/processwire/processwire/tar.gz/refs/heads/dev -O processwire-dev.tar.gz

tar -xf processwire-dev.tar.gz

cp -ru processwire-dev/* /var/www/

# kick off the upstream command:
exec /usr/local/bin/docker-php-entrypoint "$@"