version: "3.9"

networks:
  pw:
    name: pw

services:
  apache:
    container_name: ${PREFIX}apache
    build:
      context: ./apache
    volumes:
      - ./www:/var/www/html:rw
    ports:
      - 127.0.0.1:8080:80
    networks:
      - pw

  db:
    container_name: ${PREFIX}db
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - pw
