networks:
  pw:
    name: pw

services:
  apache:
    container_name: ${PWUP_PREFIX}apache
    build:
      context: ./apache
    environment:
      SITE_PROFILE: ${SITE_PROFILE}
    ports:
      - 80:80
    volumes:
      - "./:/var/www/html:rw"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pw
    healthcheck:
      test: ["CMD-SHELL", "test -f /var/www/html/site/assets/installed.php || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 30
      start_period: 5s
  
  db:
    container_name: ${PWUP_PREFIX}db
    image: mariadb:10.8.3
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - pw
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--connect"]
      interval: 30s
      timeout: 5s
      retries: 10 
      start_period: 30s
