networks:
  pw:
    name: pw

services:
  apache:
    container_name: ${PWUP_PREFIX}apache
    build:
      context: ./apache
    ports:
      - 80:80
    volumes:
      - "./www:/var/www/html:rw"
      - type: bind
        source: ./.env
        target: /var/www/html/.env
    depends_on:
      - db
    networks:
      - pw
  
  db:
    container_name: ${PWUP_PREFIX}db
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - pw
