version: "3.9"

networks:
  pw:
    name: pw

services:
  php-fpm:
    container_name: ${PREFIX}php-fpm
    build:
      context: ./php-fpm
    volumes:
      - ./www:/var/www:rw
    networks:
      - pw

  nginx:
    container_name: ${PREFIX}nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - "./www:/var/www:ro"
      - "./nginx/conf.d:/etc/nginx/templates"
    depends_on:
      - ${PREFIX}php-fpm
    networks:
      - pw
    environment:
      - PHP_FPM_SERVER=${PREFIX}php-fpm:9000
  
  db:
    container_name: ${PREFIX}db
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - pw
