version: 2.1
jobs:
  start:
    machine:
      image: ubuntu-2004:202111-02
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Start the containers
          command: |
            docker-compose up -d
      - run:
          name: Check
          command: |
            curl 127.0.0.1
      - run:
          name: Test
          command: |
            which python3

workflows:
  version: 2
  main:
    jobs:
      - start