version: 2.1
jobs:
  start:
    machine:
      image: ubuntu-2204:2022.07.1
      docker_layer_caching: true
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Start the containers
          command: |
            cp .env.example .env
            docker compose up -d --wait
      - run:
          name: Waiting for Apache
          command: |
            for i in `seq 1 20`;
            do
              nc -z 127.0.0.1 80 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Apache && exit 1
      - run:
          name: Check for the install file
          command: |
            sleep 10
            test -f site/assets/installed.php || exit 1

workflows:
  version: 2
  main:
    jobs:
      - start