#!/bin/sh

cd /tmp

curl --location --output processwire-dev.tar.gz https://github.com/processwire/processwire/archive/dev.tar.gz

tar -xf processwire-dev.tar.gz

cp -ru processwire-dev/* /var/www/html/

if [ $SITE_PROFILE != "site-blank" ]
then
    curl --location --output $SITE_PROFILE-main.tar.gz https://github.com/processwire/$SITE_PROFILE/archive/main.tar.gz

    tar -xf $SITE_PROFILE-main.tar.gz

    cp -ru $SITE_PROFILE-main /var/www/html/$SITE_PROFILE
fi

# enable apache mod_rewrite
a2enmod rewrite

# kick off the upstream command:
exec /usr/local/bin/docker-php-entrypoint "$@"